### ISSUE TITLE
WDT

### ISSUE THREAD

**Issue by lucasbrendel** [xmc-rs/xmc4-hal#49]
# Watchdog Timer

## API

- [x] new (#46)
- [x] start (#46)
- [x] stop (#46)
- [x] enable (#70)
- [x] disable (#70)
- [x] set_debug_mode (#46)
- [x] set_window_bounds (#46)
- [x] set_mode (#46)
- [x] set_service_pulse_width (#46)
- [x] get_counter (#46)
- [x] service (#46)
- [x] clear_alarm (#46)
